WebTienda/WebTienda/Areas/Inventario/Controllers/CarroComprasController.cs
using Inventory.Models.ViewModels;
using Inventory.Models;
using InventoryWeb.Data.Repositorio.IRepositorio;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using InventoryWeb.Utilities;
using InventoryWeb.Data;
using Stripe;
using Rotativa.AspNetCore;

namespace InventoryWeb.Areas.Inventario.Controllers
{
    [Area("Inventario")]
    public class CarroComprasController : Controller
    {
        private readonly IUnidadTrabajo _unidadTrabajo;
        private readonly IEmailSender _emailSender;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _db;
        [BindProperty]
        public CarroComprasVM CarroComprasVM { get; set; }
        public CarroComprasController(IUnidadTrabajo unidadTrabajo,
                                      IEmailSender emailSender,
                                      UserManager<IdentityUser> userManager,
                                      ApplicationDbContext db)
        {
            _unidadTrabajo = unidadTrabajo;
            _emailSender = emailSender;
            _userManager = userManager;
            _db = db;
        }
        public IActionResult Index()
        {
            var claimIdentidad = (ClaimsIdentity)User.Identity;
            var claim = claimIdentidad.FindFirst(ClaimTypes.NameIdentifier);

            CarroComprasVM = new CarroComprasVM()
            {
                Orden = new Inventory.Models.Orden(),
                CarroComprasLista = _unidadTrabajo.CarroCompras.ObtenerTodos(u => u.UsuarioAplicacionId ==
                                                                claim.Value, IncluirPropiedades: "Producto")
            };

            CarroComprasVM.Orden.TotalOrden = 0;
            CarroComprasVM.Orden.UsuarioAplicacion = _unidadTrabajo.UsuarioAplicacion.ObtenerPrimero(u => u.Id == claim.Value);

            foreach (var lista in CarroComprasVM.CarroComprasLista)
            {
                lista.Precio = lista.Producto.Precio;
                CarroComprasVM.Orden.TotalOrden += (lista.Precio * lista.Cantidad);
            }

            return View(CarroComprasVM);
        }
        public ActionResult mas(int carroId)
        {
            var carroCompras = _unidadTrabajo.CarroCompras.ObtenerPrimero(
                               c => c.Id == carroId, IncluirPropiedades: "Producto");
            carroCompras.Cantidad += 1;
            _unidadTrabajo.Guardar();
            return RedirectToAction(nameof(Index));
        }
        public ActionResult menos(int carroId)
        {
            var carroCompras = _unidadTrabajo.CarroCompras.ObtenerPrimero(
                               c => c.Id == carroId, IncluirPropiedades: "Producto");
           
            if(carroCompras.Cantidad == 1)
            {
                var numeroProductos = _unidadTrabajo.CarroCompras.ObtenerTodos(u =>
                                      u.UsuarioAplicacionId == carroCompras.UsuarioAplicacionId).ToList().Count();
                _unidadTrabajo.CarroCompras.Remover(carroCompras);
                _unidadTrabajo.Guardar();
                HttpContext.Session.SetInt32(DS.ssCarroCompras, numeroProductos - 1);
            }
            else
            {
                carroCompras.Cantidad -= 1;
                _unidadTrabajo.Guardar();
                return RedirectToAction(nameof(Index));
            }
            carroCompras.Cantidad += 1;
            _unidadTrabajo.Guardar();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult remover(int carroId)
        {
            var carroCompras = _unidadTrabajo.CarroCompras.ObtenerPrimero(
                  c => c.Id == carroId, IncluirPropiedades: "Producto");
            var numeroProductos = _unidadTrabajo.CarroCompras.ObtenerTodos(
                u => u.UsuarioAplicacionId == carroCompras.UsuarioAplicacionId).ToList().Count();
            _unidadTrabajo.CarroCompras.Remover(carroCompras);
            _unidadTrabajo.Guardar();
            HttpContext.Session.SetInt32(DS.ssCarroCompras, numeroProductos - 1);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
      public IActionResult Proceder()
        {
            var claimIdentidad = (ClaimsIdentity)User.Identity;
            var claim = claimIdentidad.FindFirst(ClaimTypes.NameIdentifier);
            CarroComprasVM = new CarroComprasVM()
            {
                Orden = new Inventory.Models.Orden(),
                CarroComprasLista = _unidadTrabajo.CarroCompras.ObtenerTodos(u => u.UsuarioAplicacionId ==
                                                                claim.Value, IncluirPropiedades: "Producto"),
                //para controlar que se respete el stock de inventario de una bodega al momento de la venta
                Compania = _unidadTrabajo.Compania.ObtenerPrimero()
            };
            CarroComprasVM.Orden.TotalOrden = 0;
            CarroComprasVM.Orden.UsuarioAplicacion = _unidadTrabajo.UsuarioAplicacion.ObtenerPrimero(u => u.Id == claim.Value);
            foreach (var lista in CarroComprasVM.CarroComprasLista)
            {
                lista.Precio = lista.Producto.Precio;
                CarroComprasVM.Orden.TotalOrden += (lista.Precio * lista.Cantidad);
            }
            CarroComprasVM.Orden.NombreCliente = CarroComprasVM.Orden.UsuarioAplicacion.Nombres + " " +
                                                  CarroComprasVM.Orden.UsuarioAplicacion.Apellidos;
            CarroComprasVM.Orden.Telefono = CarroComprasVM.Orden.UsuarioAplicacion.Telefono;
            CarroComprasVM.Orden.Direccion = CarroComprasVM.Orden.UsuarioAplicacion.Direccion;
            CarroComprasVM.Orden.Pais = CarroComprasVM.Orden.UsuarioAplicacion.Pais;
            CarroComprasVM.Orden.Ciudad = CarroComprasVM.Orden.UsuarioAplicacion.Ciudad;
            //Controlar stock 
            foreach (var item in CarroComprasVM.CarroComprasLista)
            {
                //capturar el stock de cada producto
                var producto = _db.BodegaProducto.FirstOrDefault(
                                  b => b.ProductoId == item.ProductoId &&
                                  b.BodegaId == CarroComprasVM.Compania.BodegaVentaId);
                if (item.Cantidad > producto.Cantidad){
                    TempData["Error"] = " La cantidad del producto " + item.Producto.Descripcion
                                        + " excede la cantidad que tiene el inventario " + producto.Cantidad;
                    //que se quede en el index y no vaya al Post
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(CarroComprasVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Proceder")]
        public IActionResult ProcederPost(string stripeToken)
        {
            var claimIdentidad = (ClaimsIdentity)User.Identity;
            var claim = claimIdentidad.FindFirst(ClaimTypes.NameIdentifier);
            CarroComprasVM.Orden.UsuarioAplicacion = _unidadTrabajo.UsuarioAplicacion.ObtenerPrimero(c => c.Id == claim.Value);
            CarroComprasVM.CarroComprasLista = _unidadTrabajo.CarroCompras.ObtenerTodos(
                                                    c => c.UsuarioAplicacionId == claim.Value, IncluirPropiedades: "Producto");
            CarroComprasVM.Orden.EstadoOrden = DS.EstadoPendiente;
            CarroComprasVM.Orden.EstadoPago = DS.PagoEstadoPendiente;
            CarroComprasVM.Orden.UsuarioAplicacionId = claim.Value;
            CarroComprasVM.Orden.FechaOrden = DateTime.Now;

            //Para descarga del inventario
            CarroComprasVM.Compania = _unidadTrabajo.Compania.ObtenerPrimero();


            _unidadTrabajo.Orden.Agregar(CarroComprasVM.Orden);
            _unidadTrabajo.Guardar();

            foreach (var item in CarroComprasVM.CarroComprasLista)
            {
                OrdenDetalle ordenDetalle = new OrdenDetalle()
                {
                    ProductoId = item.ProductoId,
                    OrdenId = CarroComprasVM.Orden.Id,
                    Precio = item.Producto.Precio,
                    Cantidad = item.Cantidad
                };
                CarroComprasVM.Orden.TotalOrden += ordenDetalle.Cantidad * ordenDetalle.Precio;
                _unidadTrabajo.OrdenDetalle.Agregar(ordenDetalle);

            }
            // Remover los productos del carro de Compras
            _unidadTrabajo.CarroCompras.RemoverRango(CarroComprasVM.CarroComprasLista);
            _unidadTrabajo.Guardar();
            HttpContext.Session.SetInt32(DS.ssCarroCompras, 0);

            if (stripeToken == null)
            {

            }
            else
            {
                //Procesar el Pago
                var options = new ChargeCreateOptions
                {
                    Amount = Convert.ToInt32(CarroComprasVM.Orden.TotalOrden * 100),
                    Currency = "usd",
                    Description = "Numero de Orden: " + CarroComprasVM.Orden.Id,
                    Source = stripeToken
                };
                var service = new ChargeService();
                Charge charge = service.Create(options);
                if (charge.BalanceTransactionId == null)
                {
                    CarroComprasVM.Orden.EstadoPago = DS.EstadoRechazado;
                }
                else
                {
                    CarroComprasVM.Orden.TransaccionId = charge.BalanceTransactionId;
                    //CarroComprasVM.Orden.TransaccionId = charge.Id;
                }
                if (charge.Status.ToLower() == "succeeded")
                {
                    CarroComprasVM.Orden.EstadoPago = DS.PagoEstadoAprobado;

WebTienda/WebTienda/Areas/Inventario/Views/CarroCompras/ImprimirOrden.cshtml
@model Inventory.Models.ViewModels.CarroComprasVM
@using System.Globalization
@{
    ViewData["Title"] = "ImprimirOrden";
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    <div class="row">
        <div class="col-sm-4">
            <img src="@Model.Compania.LogoUrl" class="rounded" width="250" height="200" />
        </div>
        <div class="col-sm-4">
            <label class="col-form-label" style="font-size:20px;">@Model.Compania.Nombre</label>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-2">
            <label class="col-form-label" style="font-weight:bold; font-size:40px;">
                Order#
            </label>
        </div>
        <div class="col-2" style="border: none;">
            <label class="col-form-label" style="font-weight:bold; font-size:40px;">@Model.Orden.Id</label>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-2">
            <label class="col-form-label" style="font-weight:bold; font-size:20px;">
                Compania:
            </label>
        </div>
        <div class="col-4" style="border: none;">
            <label class="col-form-label" style="font-size:20px;">@Model.Compania.Nombre</label>
        </div>
        <div class="col-6" style="border: none;">
            <label class="col-form-label" style="font-size:20px;">
                @Model.Compania.Direccion ,
            @Model.Compania.Ciudad , @Model.Compania.Pais
        </label>
    </div>
</div>
<div class="form-group row">
    <div class="col-2">
        <label class="col-form-label" style="font-weight: bold; font-size:20px;">Cliente:</label>
    </div>
    <div class="col-6">
        <label class="col-form-label" style="font-size:20px;">@Model.Orden.NombreCliente</label>
    </div>
</div>
<div class="form-group row">
    <div class="col-2">
        <label class="col-form-label" style="font-weight: bold; font-size:20px;">Fecha Orden:</label>
    </div>
    <div class="col-6">
        <label class="col-form-label" style="font-size:20px;">@Model.Orden.FechaOrden</label>
    </div>
</div>
<div>
    <table class="table table-striped border" style="height:10px;">
        <thead class="thead-dark">
            <tr class="table-secondary thead-dark">
                <th style="font-weight: bold; font-size:20px;">
                    Producto
                </th>
                <th style="text-align:right; font-weight: bold; font-size:20px;">
                    Precio
                </th>
                <th style="text-align:right; font-weight: bold; font-size:20px;">
                    Cantidad
                </th>
            </tr>
        <thead>
        <tbody style="height:10px;">
            @foreach (var item in Model.OrdenDetalleLista)
            {
                <tr>
                    <td style="font-size:20px;">
                        @Html.DisplayFor(m => item.Producto.Descripcion)
                    </td>

                    <td style="text-align:right;font-size:20px;">
                        @Html.DisplayFor(m => item.Precio)
                    </td>
                    <td style="text-align:right;font-size:20px;">
                        @Html.DisplayFor(m => item.Cantidad)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<br />
<div class="form-group row">
    <div class="col-8">
    </div>
    <div class="col-2">
        <label class="col-form-label" style="font-weight: bold;font-size:20px;">Total Orden:</label>
    </div>
    <div class="col-2" style="text-align:right; font-size:20px;">
        <label class="col-form-label">@(Model.Orden.TotalOrden.ToString("C2"))</label>
    </div>
</div>
</body>

</html>

WebTienda/WebTienda/Areas/Inventario/Views/CarroCompras/Index.cshtml
@model Inventory.Models.ViewModels.CarroComprasVM
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
@if (TempData["Error"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show mt-5" role="alert">
        <h4>@TempData["Error"]</h4>
        <button type="button" class="close" data-dismiss="alert"
                arial-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
<form method="post">
    <br />
    @if (Model.CarroComprasLista.Count() > 0)
    {
        <div>
            <div class="container mt-4">
                <div class="card">
                    <div class="card-header bg-dark text-light ml-0 row container">
                        <div class="col-6">
                            <i class="fa fa-shopping-cart"></i> &nbsp;
                            Carro de Compras
                        </div>
                        <div class="col-6 text-right">
                            <a asp-area="Inventario" asp-controller="Home"
                               asp-action="Index"
                               class="btn btn-outline-info btn-close-white btn-sm">Seguir Comprando</a>
                        </div>
                    </div>
                    <div class="card-body">
                        @foreach (var item in Model.CarroComprasLista)
                        {
                        <div class="row">
                           
                            <div class="d-none d-lg-block col-lg-1 text-center py-2">
                                <br />
                                <img src="@item.Producto.ImageUrl" class="rounded" width="100" />

                            </div>

                            <div class="col-12 text-sm-center col-lg-6 text-lg-left">


                                <h5><strong> @item.Producto.Descripcion</strong></h5>
                            </div>
                            <div class="col-12 text-sm-center col-lg-5 text-lg-right row">
                                <div class="col-4 text-md-right" style="padding-top:5px;">
                                    <h6>
                                        <strong>
                                            ₡@item.Producto.Precio<span class="text-muted">x</span> @item.Cantidad
                                        </strong>
                                    </h6>
                                </div>
                                <div class="col-6 col-sm-4 col-lg-6">
                                    <div class="float-right mx-1">
                                        <a asp-action="mas" asp-route-carroId="@item.Id"
                                           class="btn btn-primary">
                                            <i class="fas fa-plus"></i>
                                        </a>
                                    </div>
                                    <div class="float-right mx-1">
                                        <a asp-action="menos" asp-route-carroId="@item.Id"
                                           class="btn btn-danger">
                                            <i class="fas fa-minus"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-2 col-sm-4 col-lg-2 text-right">
                                    <a asp-action="remover" asp-route-carroId="@item.Id"
                                       class="btn btn-outline-danger">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                            <hr />
                        }

                        <div class="row">
                            <div class="col-12 col-md-6 offset-md-6 col-lg-4 offset-lg-8 pr-4">
                                <ul class="list-group">
                                    <li class="list-group-item d-flex justify-content-between bg-light">

                                        <samp class="text-info">Total (CR)</samp>
                                        <strong class="text-info">
                                            ₡
                                            <span id="txtTotalOrden">@Model.Orden.TotalOrden</span>
                                        </strong>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <br />
                        <br />

                        <br />
                        <br />
                        <span class="text-dark">Nuestra tienda de ropa ofrece a nuestros clientes una gama de productos de alta calidad a precios muy competitivos. </span>
                        <br />
                        <span class="text-dark">Todos los productos son nuevos y están en perfectas condiciones.  </span>
                        <br />
                        <span class="text-dark">Nos esforzamos por ofrecer un servicio excelente a todos nuestros clientes y hacemos todo lo posible para responder a sus consultas y pedidos de manera rápida y eficiente. </span>
                        <br />
                        <span class="text-dark">Si no está satisfecho con su compra, por favor, póngase en contacto con nosotros y haremos todo lo posible para solucionar el problema.  </span>
                        <br />
                        <span class="text-dark"> Cualquier prenda despachada por nosotros es registrada y autorizada por Gucci International Inc. Gucci se reserva el derecho de cambiar estos términos y condiciones en cualquier momento.  </span>
                        <br />
                        <span class="text-dark">Los cambios tendrán efecto inmediato en el momento en que se publiquen en el sitio web. Al utilizar el sitio web después de que se hayan publicado los cambios, usted acepta los términos y condiciones modificados. </span>
                        <br/>
                        <INPUT type="checkbox" onclick="ActivarBtn()" id="term">
                        <span class="text-danger"> Terminos y condiciones </span>
                    </div>
                    <div class="card-footer">
                        <div class="card-footer row">
                            <div class="col-sm-12 col-lg-4 col-md-6 offset-lg-8 offset-md-6 ">
                                <a asp-area="Inventario" asp-controller="CarroCompras"
                                   asp-action="Proceder" class="btn btn-success form-control"> Proceder con la compra</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</form>

WebTienda/WebTienda/Areas/Inventario/Views/CarroCompras/OrdenConfirmacion.cshtml
@model int
<div class="container row">
    <div class="col-12 text-center">
        <h1 class="text-dark text-center">GRACIAS POR PREFERIRNOS!!!</h1><br />
        <br />
        <br />
        <h1 class="text-dark text-center">Orden Procesada correctamente!!!</h1><br />

  
       
    </div>
    <div class="col-12 text-center" style="color:black">
        <br />
        Gracias Por tu Orden! <br />
        Hemos recibido tu Orden y Nosotros te enviaremos un email pronto!
        <br />
        Su número de orden es : @Model
        <br />
        <br />

        
        <br />
        <br />
        <div class="text-center">
            <a asp-area="Inventario" asp-controller="Home"
               asp-action="Index" class="btn btn-success">
                Salir
            </a>
            <a asp-action="ImprimirOrden" class="btn btn-warning"
               asp-route-id="@Model" target="_blank">
                <i class="fas fa-print"></i>
                Imprimir
            </a>
        </div>
    </div>
</div>

WebTienda/WebTienda/Areas/Inventario/Views/CarroCompras/Proceder.cshtml
@model Inventory.Models.ViewModels.CarroComprasVM
@using Microsoft.Extensions.Options
@using System.Globalization
@inject IOptions<InventoryWeb.Utilities.StripeSettings> Stripe
<form method="post">
    <br />   <br />
    <div class="backgroundWhiteBorder mt-5">
        <div class="container">
            <div class="card">
                <div class="card-header bg-dark text-light ml-0 row container">
                    <div class="col-6">
                        <i class="fa fa-shopping-cart"></i> &nbsp;
                        Detalles de la Orden
                    </div>
                    <div class="col-6 text-right">
                        <a asp-area="Inventario" asp-controller="CarroCompras"
                           asp-action="Index" class="btn btn-outline-info btn-close-white btn-sm">Regresar al Carro</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="container rounded p-2">
                        <div class="row">
                            <div class="col-12 col-lg-6 pb-4">
                                <div class="row">
                                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                                        <span class="text-info text-dark">Detalles de Envío:</span>
                                    </h4>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Cliente:</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Orden.NombreCliente" type="text" class="form-control" />
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Telefono</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Orden.Telefono" type="text" class="form-control" />
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Direccion</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Orden.Direccion" type="text" class="form-control" />
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Ciudad</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Orden.Ciudad" type="text" class="form-control" />
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label>Pais</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Orden.Pais" type="text" class="form-control" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-lg-5 offset-lg-1">
                                <h4 class="d-flex justify-content-between align-items-center mb-3">
                                    <span class="text-info text-dark">Productos:</span>
                                </h4>
                                <ul class="list-group mb-3">
                                    @foreach (var item in Model.CarroComprasLista)
                                    {
                                        <li class="list-group-item d-flex justify-content-between">
                                            <div>
                                                <h6 class="my-0">@item.Producto.Descripcion</h6>
                                                <small class="text-muted">Cantidad: @item.Cantidad</small>
                                            </div>
                                            <span class="text-muted">₡ @(item.Producto.Precio * item.Cantidad)</span>
                                        </li>
                                    }

                                    <li class="list-group-item d-flex justify-content-between bg-light">
                                        <small class="text-info">Total (USD)</small>
                                        <strong class="text-info">@(Model.Orden.TotalOrden)</strong>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-12 col-md-8 pt-2">
                            <p style="color:maroon; font-size:14px;">
                                Fecha Estimada de Envío: @DateTime.Now.AddDays(7).ToShortDateString() -
                                @DateTime.Now.AddDays(14).ToShortDateString()
                            </p>
                        </div>
                        <div class="col-12 col-md-4">
                            @{
                                var TotalOrdenStripe = Model.Orden.TotalOrden * 100;
                            }
                            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                    data-key="@Stripe.Value.PublishableKey"
                                    data-amount="@TotalOrdenStripe"
                                    data-name="Sistema Inventario"
                                    data-label="Realizar Pedido"
                                    data-description="Compra de ropa en linea"
                                    data-locale="auto"
                                    data-allow-remember-me="false"
                                    data-image="https://stripe.com/img/documentation/checkout/marketplace.png">
                            </script>
                            <script>
                                document.getElementsByClassName("stripe-button-el")[0].style.display = 'none';
                            </script>
                            <button type="submit" value="Realizar Pedido"
                                    class="btn btn-success form-control">
                                Realizar Pedido
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>